use_frameworks!

target 'SPBZoomTransition_Example' do
  pod 'SPBZoomTransition', :path => '../'
  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher', :branch => 'swift3', :commit => '585f035e1db1420fc9e6df2aa12ba628b5cf79e6'

  target 'SPBZoomTransition_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
